python main.py --dataset=citeulike --backbone=jgcf --model=dcdoptim4 --gpu_id=2 --cfg dcd_negx=10
python main.py --dataset=citeulike --backbone=jgcf --model=dcdoptim4 --gpu_id=2 --cfg dcd_negx=5
python main.py --dataset=citeulike --backbone=jgcf --model=dcdoptim4 --gpu_id=2 --cfg dcd_negx=2
python main.py --dataset=citeulike --backbone=jgcf --model=dcdoptim4 --gpu_id=2 --cfg dcd_negx=1
python main.py --dataset=citeulike --backbone=jgcf --model=dcdoptim4 --gpu_id=2 --cfg dcd_negx=0.5
python main.py --dataset=citeulike --backbone=jgcf --model=dcdoptim4 --gpu_id=2 --cfg dcd_negx=0.3
python main.py --dataset=citeulike --backbone=jgcf --model=dcdoptim4 --gpu_id=2 --cfg dcd_negx=0.1
python main.py --dataset=citeulike --backbone=jgcf --model=dcdoptim4 --gpu_id=2 --cfg dcd_negx=0
python main.py --dataset=citeulike --backbone=jgcf --model=dcdoptim4 --gpu_id=2 --cfg dcd_negx=-0.1
python main.py --dataset=citeulike --backbone=jgcf --model=dcdoptim4 --gpu_id=2 --cfg dcd_negx=-0.3
python main.py --dataset=citeulike --backbone=jgcf --model=dcdoptim4 --gpu_id=2 --cfg dcd_negx=-0.5
python main.py --dataset=citeulike --backbone=jgcf --model=dcdoptim4 --gpu_id=2 --cfg dcd_negx=-1
python main.py --dataset=citeulike --backbone=jgcf --model=dcdoptim4 --gpu_id=2 --cfg dcd_negx=2
python main.py --dataset=citeulike --backbone=jgcf --model=dcdoptim4 --gpu_id=2 --cfg dcd_negx=-5
python main.py --dataset=citeulike --backbone=jgcf --model=dcdoptim4 --gpu_id=2 --cfg dcd_negx=-10
