epochs: 1000
batch_size: 2048
lr: 1.e-3
wd: 1.e-5
lmbda: 0.01

mrrd_K: 50
mrrd_L: 100
mrrd_T: 10
mrrd_mxK: 500
mrrd_beta: 0
mrrd_tau: 1
mrrd_gamma: 1
no_sort: 0
loss_type: rrd
sample_rank: True
mrrd_test_type: 0