epochs: 1000
batch_size: 2048
lr: 1.e-3
wd: 1.e-5
lmbda: 0.01

rrd_K: 50
rrd_L: 100
rrd_T: 10
rrd_mxK: 500
rrd_unselected: 0
rrd_neg: 1.5
calu_len: 5
rrd_extra: 1000
mode: "val_diff_2"
alpha: 100
neg_T: 100
sample_type_for_extra: "T_val_with_uninteresting"
T_for_extra: 1
mx_T: 100
test_type: 0