epochs: 1000
batch_size: 2048
lr: 1.e-4
wd: 1.e-6
num_ns: 2000
neg_sampling_on_all: True

rrd_K: 100
rrd_L: 200
rrd_T: 10
rrd_mxK: 500
rrd_unselected: 0
rrd_neg: 1.5
calu_len: 5
mode: "val_diff_2"
alpha: 0.1
neg_T: 1
rrd_extra: 1000
mx_T: 100
T_for_extra: 1
sample_type_for_extra: "T_val_with_uninteresting"
