epochs: 1000
batch_size: 256
lr: 1.e-4
wd: 1.e-5
num_ns: 2000
neg_sampling_on_all: True

rrd_K: 40
rrd_L: 40
rrd_T: 10
rrd_mxK: 500
rrd_unselected: 0
rrd_neg: 1.5
calu_len: 5
rrd_extra: 5000
mode: 'None'
alpha: 1
neg_T: 1
sample_type_for_extra: "random_regardless_uninteresting"
T_for_extra: 1
mx_T: 50